### ISSUE TITLE
Relocate accumulo-proxy to separate repository on its own release schedule

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo-proxy#3]
accumulo-proxy is really a separate project from the core Accumulo distribution, and I think it should be shipped separately, and maintained separately in its own repo.

This will also help isolate the maintenance interest, so that if there isn't any current interest, no time is wasted on it, and if there is, work can be done independently from the releases of the core Accumulo distribution.

**Comment by ctubbsii** [comment]
@hkeebler I transferred this issue from apache/accumulo#454 to this accumulo-proxy project, because all the work needed to be done is in this repository.

**Comment by ctubbsii** [comment]
> @ctubbsii the accumulo-proxy contrib subdirectory has a create-release-candidate.sh script which does not exist in the accumulo project. I'm not sure what it does and why it is there. Just curious.

Accumulo has a script to prepare release candidates for voting. Moving this to its own repository means it would be released separately. So, that file was added to make it more convenient to release new versions of the proxy.

**Comment by hkeebler** [comment]
@ctubbsii I assume you want the integrated tests in this project.  I'm having trouble getting them to run.  They seem to hang logging into the client -  `ByteBuffer login = client.login("root", properties);`   
When trying the debug process I lose the drill down.  Any ideas off the top of your head?

**Comment by hkeebler** [comment]
Re-phrasing the last question.  It is hanging because the Tserver cannot use the accumulo native libs.  If I set `cfg.setProperty(Property.TSERV_NATIVEMAP_ENABLED, "false");` then it runs.  BUT I probably should figure out how to get the native lib to build in the test scenario.  Looking into that now.

**Comment by hkeebler** [comment]
Actually I am going with leaving the native libs as false unless someone thinks otherwise.  Additionally,  It ooks like the "thrift" generated code is checked into the git repository.  Should it be?

**Comment by ctubbsii** [comment]
Without the native libs is fine. These ITs don't need to assume the native libs exist.

**Comment by ctubbsii** [comment]
Generally, we check in the thrift code during development, because they don't change very often, and not all developers have thrift installed (because it's a pain to build from source, and most distros don't have the right version in an RPM/DEB). We tend to regenerate them whenever we make a thrift change, or when we do releases.
