### ISSUE TITLE
Failing test - testSiteConfiguration()

### ISSUE THREAD

**Issue by DomGarguilo** [apache/accumulo-proxy#43]
This test now fails after the changes made in #42. Based on some discussion on that ticket ([linked here](https://github.com/apache/accumulo-proxy/pull/42#issuecomment-1317688942)), it may be the case that this test should be removed or replaced entirely.

**Comment by ctubbsii** [comment]
This seems related to #16

**Comment by DomGarguilo** [comment]
Closing as completed by #59
