### ISSUE TITLE
Failing test - userAuthentication()

### ISSUE THREAD

**Issue by DomGarguilo** [apache/accumulo-proxy#44]
This test now fails after the changes made in #42. Based on some discussion on that ticket ([linked here](https://github.com/apache/accumulo-proxy/pull/42#issuecomment-1317688942)), it may be the case that this test should be removed or replaced entirely.

**Comment by ctubbsii** [comment]
This seems related to #16

**Comment by ctubbsii** [comment]
I am not looking at the code at the moment, but I suspect we don't need this method implemented in the proxy at all. Once removed, the test would be removed as well.

**Comment by DomGarguilo** [comment]
Closing as completed by #59
