### ISSUE TITLE
Create tarball with scripts for running proxy.

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo-proxy#5]
I think it would be useful if the build created a tarball containing at least the following items.  This would make it easy for a user to run the proxy.

| File | Description |
|------|----------------|
| conf/proxy-env.sh | Bash code that sets up the classpath with deps like accumulo |
| conf/proxy.properties | Properties needed for Accumulo and the proxy |
| lib/accumulo2-proxy-1.0.0.jar | The proxy java code |
| bin/accumulo-proxy | A script that sources proxy-env.sh and then runs the proxy passing in proxy.properties |

The source for the scripts and configuration could be placed in `src/main/scripts` and `src/main/config` in this repo.

**Comment by keith-turner** [comment]
Actually building the tarball would be done via the maven assembly plugin.   Accumulo and Fluo use this build their tarballs.

**Comment by ctubbsii** [comment]
A tarball would also include LICENSE/NOTICE/README files (just mentioning for completeness). And, should also contain the `*.thrift` files and instructions on how to generate language-specific bindings.

**Comment by mikewalch** [comment]
@mjwall, are you still working on this?  If not, I would like to work on it.

**Comment by mjwall** [comment]
> @mjwall, are you still working on this? If not, I would like to work on it.

Feel free @mikewalch
