### ISSUE TITLE
Add cpp example client file

### ISSUE THREAD

**Issue by DomGarguilo** [apache/accumulo-proxy#53]
There are example client files that can be run with ruby and python which seem helpful. I created this ticket to propose the idea of creating a similar file to test the cpp.

**Comment by ctubbsii** [comment]
I don't think we need that. The main reason to use python or ruby with the proxy is to lower the barrier for people who are more comfortable with scripting languages. It's unlikely that CPP developers would use it. if they do, they probably don't need help with an example.
