### ISSUE TITLE
Ensure proxy works well in docker

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo-proxy#8]
Not sure all that this entails.  When making Fluo and Accumulo work well in docker it was important that the script could accept options on the command line.  Would be nice if the proxy script also did this, so could do something like.

```
docker run accumulo-proxy -o proxyopt1=foo -o proxyopt2=foofoo
```

Also, if the default proxy log4j config just prints stuff to stdout, this works nicely when running in docker.

This is related to #5

**Comment by volmasoft** [comment]
I'll take a bash at this next week if no one else picks it up (which I suspect not given the age :))

**Comment by volmasoft** [comment]
@keith-turner In case you've not seen it, a WIP pull request with questions is now open here: https://github.com/apache/accumulo-proxy/pull/20

**Comment by keith-turner** [comment]
Done in #20
